In [1]:
import pandas as pd

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
data = pd.read_excel("iris.xlsx")

In [16]:
data.head()

   sepallength  sepalwidth  petallength  petalwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         2.6          6.9         2.3  Iris-virginica
2          7.7         2.8          6.7         2.0  Iris-virginica
3          7.7         3.0          6.1         2.3  Iris-virginica
4          7.7         3.8          6.7         2.2  Iris-virginica

In [17]:
x = data.iloc[: , :-1]

In [18]:
x

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         2.6          6.9         2.3
2            7.7         2.8          6.7         2.0
3            7.7         3.0          6.1         2.3
4            7.7         3.8          6.7         2.2
..           ...         ...          ...         ...
105          4.5         2.3          1.3         0.3
106          4.4         2.9          1.4         0.2
107          4.4         3.0          1.3         0.2
108          4.4         3.2          1.3         0.2
109          4.3         3.0          1.1         0.1

[110 rows x 4 columns]

In [19]:
y = data.iloc[: , -1]

In [20]:
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
105       Iris-setosa
106       Iris-setosa
107       Iris-setosa
108       Iris-setosa
109       Iris-setosa
Name: class, Length: 110, dtype: object

In [21]:
model = RandomForestClassifier()

In [25]:
model.fit(x.values,y.values)

RandomForestClassifier()

In [26]:
predictions = model.predict([[5.6,	2.9 ,	3.6	, 1.3]])

In [27]:
predictions

array(['Iris-versicolor'], dtype=object)

In [28]:
datat = pd.read_excel("iris_test.xlsx")

In [33]:
x_test= datat.iloc[: , :-1]

In [34]:
x_test

    sepallength  sepalwidth  petallength  petalwidth
0           6.0         3.0          4.8         1.8
1           6.0         3.4          4.5         1.6
2           5.9         3.0          5.1         1.8
3           5.9         3.0          4.2         1.5
4           5.9         3.2          4.8         1.8
5           5.8         2.6          4.0         1.2
6           5.8         2.7          5.1         1.9
7           5.8         2.7          5.1         1.9
8           5.8         2.7          4.1         1.0
9           5.8         2.7          3.9         1.2
10          5.8         2.8          5.1         2.4
11          5.8         4.0          1.2         0.2
12          5.7         2.5          5.0         2.0
13          5.7         2.6          3.5         1.0
14          5.7         2.8          4.5         1.3
15          5.7         2.8          4.1         1.3
16          5.7         2.9          4.2         1.3
17          5.7         3.0          4.2         1.2
18          5.7         3.8          1.7         0.3
19          5.7         4.4          1.5         0.4
20          5.6         2.5          3.9         1.1
21          5.6         2.7          4.2         1.3
22          5.6         2.8          4.9         2.0
23          5.6         2.9          3.6         1.3
24          5.6         3.0          4.5         1.5
25          5.6         3.0          4.1         1.3
26          5.5         2.3          4.0         1.3
27          5.5         2.4          3.8         1.1
28          5.5         2.4          3.7         1.0
29          5.5         2.5          4.0         1.3
30          5.5         2.6          4.4         1.2
31          5.5         3.5          1.3         0.2
32          5.5         4.2          1.4         0.2
33          5.4         3.0          4.5         1.5

In [35]:
predictions = model.predict(x_test.values)

In [36]:
predictions

array(['Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor'], dtype=object)